BEGIN;

ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS subtotal        NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS discount_amount NUMERIC(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS discount_code   TEXT,
  ADD COLUMN IF NOT EXISTS tax_amount      NUMERIC(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS amount_paid     NUMERIC(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS receipt_number  TEXT UNIQUE,
  ADD COLUMN IF NOT EXISTS paid_at         TIMESTAMP;

COMMIT;
