-- 113_vendor_shop_id.sql
-- Shop ID (September 2026) - every seller gets a short public Shop ID on
-- their own profile, used for support and reference.
--
-- Format: 'UG' + a sequential number (padded to >=3 digits) + 2 random
-- uppercase letters, generated by server/utils/shopId.js's generateShopId().
-- The sequence guarantees uniqueness on its own; the letters just match
-- the channel's visual shape. Assigned once, at vendor approval (see
-- vendorController.js's approveVendor), and backfilled below for any
-- vendor already approved before this migration.

BEGIN;

CREATE SEQUENCE IF NOT EXISTS public.vendor_shop_id_seq START WITH 100;

ALTER TABLE public.vendors
    ADD COLUMN IF NOT EXISTS shop_id VARCHAR(12);

CREATE UNIQUE INDEX IF NOT EXISTS idx_vendors_shop_id_unique
    ON public.vendors (shop_id)
    WHERE shop_id IS NOT NULL;

COMMENT ON COLUMN public.vendors.shop_id IS
    'Public seller identifier shown to the vendor themselves (- Channel calls this the Shop ID). Assigned once at approval via generateShopId(); NULL for vendors never approved. Not a secret - fine to show in the vendor dashboard and admin panel, unlike the commission rate.';

-- Backfill: every already-approved vendor without one gets a shop_id now,
-- using the same sequence+random-letters shape the app generates going
-- forward, so nothing here diverges from generateShopId()'s own format.
DO $$
DECLARE
    r RECORD;
    letters TEXT;
    letter_pool TEXT := 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    new_id TEXT;
BEGIN
    FOR r IN SELECT id FROM public.vendors WHERE status = 'approved' AND shop_id IS NULL ORDER BY id ASC LOOP
        letters := '';
        FOR i IN 1..2 LOOP
            letters := letters || substr(letter_pool, 1 + floor(random() * length(letter_pool))::int, 1);
        END LOOP;
        new_id := 'UG' || lpad(nextval('public.vendor_shop_id_seq')::text, 3, '0') || letters;
        UPDATE public.vendors SET shop_id = new_id WHERE id = r.id;
    END LOOP;
END $$;

INSERT INTO public.schema_migrations (filename, note)
VALUES (
    '113_vendor_shop_id.sql',
    'Shop ID (): vendors.shop_id + vendor_shop_id_seq, assigned at approval, backfilled for already-approved vendors.'
)
ON CONFLICT (filename) DO NOTHING;

COMMIT;
