-- 127_products_lizimas_sku.sql
-- Lizimas Store SKU (Ryan, Sept 2026 - Jumia's "Jumia SKU" vs "Seller SKU").
--
--   products.sku          = Seller SKU: the vendor's own code (free text).
--                           When a vendor leaves it blank the app still fills
--                           it with a generated code, as before.
--   products.lizimas_sku  = Lizimas Store SKU: always generated by Lizimas,
--                           unique, never changes. Same format as
--                           server/utils/sku.js: {PREFIX}{10 A-Z0-9}LZMS,
--                           PREFIX = first 2 letters of the brand for vendor
--                           products, LS for staff products / no brand.
--
-- Filled by a BEFORE INSERT trigger, so every insert path (vendor form,
-- staff form, CSV import, Jumia sync) gets one without code changes.
-- Existing products: a generated-looking Seller SKU (…LZMS, unique) is
-- reused as the Lizimas Store SKU so codes vendors already see stay valid;
-- everything else gets a new code.

BEGIN;

ALTER TABLE products ADD COLUMN IF NOT EXISTS lizimas_sku VARCHAR(32);

CREATE OR REPLACE FUNCTION public.lizimas_sku_generate(p_brand TEXT, p_vendor_id INTEGER)
RETURNS TEXT AS $$
DECLARE
    chars  TEXT := 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    prefix TEXT;
    code   TEXT := '';
BEGIN
    IF p_vendor_id IS NULL OR length(btrim(coalesce(p_brand, ''))) < 2 THEN
        prefix := 'LS';
    ELSE
        prefix := upper(substr(btrim(p_brand), 1, 2));
    END IF;
    FOR i IN 1..10 LOOP
        code := code || substr(chars, 1 + floor(random() * 36)::int, 1);
    END LOOP;
    RETURN prefix || code || 'LZMS';
END;
$$ LANGUAGE plpgsql VOLATILE;

-- Backfill 1: reuse unique generated-looking seller SKUs.
UPDATE products p
SET lizimas_sku = p.sku
WHERE p.lizimas_sku IS NULL
  AND p.sku ~ '^[A-Z0-9]{12}LZMS$'
  AND (SELECT count(*) FROM products q WHERE q.sku = p.sku) = 1;

-- Backfill 2: generate the rest.
UPDATE products
SET lizimas_sku = public.lizimas_sku_generate(brand, vendor_id)
WHERE lizimas_sku IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_products_lizimas_sku ON products (lizimas_sku);
ALTER TABLE products ALTER COLUMN lizimas_sku SET NOT NULL;

CREATE OR REPLACE FUNCTION public.products_lizimas_sku_trg()
RETURNS TRIGGER AS $$
DECLARE
    candidate TEXT;
BEGIN
    IF TG_OP = 'UPDATE' THEN
        -- Lizimas Store SKU never changes once issued.
        IF OLD.lizimas_sku IS NOT NULL THEN
            NEW.lizimas_sku := OLD.lizimas_sku;
        END IF;
        RETURN NEW;
    END IF;
    IF NEW.lizimas_sku IS NOT NULL THEN
        RETURN NEW;
    END IF;
    IF NEW.sku ~ '^[A-Z0-9]{12}LZMS$'
       AND NOT EXISTS (SELECT 1 FROM products WHERE lizimas_sku = NEW.sku) THEN
        NEW.lizimas_sku := NEW.sku;
        RETURN NEW;
    END IF;
    LOOP
        candidate := public.lizimas_sku_generate(NEW.brand, NEW.vendor_id);
        EXIT WHEN NOT EXISTS (SELECT 1 FROM products WHERE lizimas_sku = candidate);
    END LOOP;
    NEW.lizimas_sku := candidate;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_products_lizimas_sku ON products;
CREATE TRIGGER trg_products_lizimas_sku
    BEFORE INSERT OR UPDATE OF lizimas_sku ON products
    FOR EACH ROW EXECUTE FUNCTION public.products_lizimas_sku_trg();

COMMENT ON COLUMN products.lizimas_sku IS
    'Lizimas Store SKU - generated by trigger trg_products_lizimas_sku, unique and immutable. products.sku is the vendor''s Seller SKU.';

INSERT INTO public.schema_migrations (filename, note)
VALUES (
    '127_products_lizimas_sku.sql',
    'products.lizimas_sku: generated, unique, immutable Lizimas Store SKU (trigger-filled on insert); products.sku stays the Seller SKU.'
)
ON CONFLICT (filename) DO NOTHING;

COMMIT;
