'use strict';

const crypto = require('crypto');
const { STATUS } = require('../stateMachine');

/**
 * MTN MoMo Collection adapter.
 *
 * Notes that bit me / will bit you:
 *  - X-Reference-Id is generated by US and is the status-lookup key. It is our
 *    external_ref. There is no other handle on the transaction.
 *  - Sandbox only accepts EUR. Production Uganda is UGX. Env-driven.
 *  - UGX is zero-decimal: send whole shillings, no cents.
 *  - Callbacks are NOT signed. Treat them as "go look now", nothing more.
 *  - Callbacks are also frequently not delivered at all. The reconciler is not
 *    a nicety here, it is the primary path.
 */

const BASE_URL = process.env.MOMO_BASE_URL;                 // https://sandbox.momodeveloper.mtn.com | https://proxy.momoapi.mtn.com
const SUB_KEY = process.env.MOMO_COLLECTION_SUBSCRIPTION_KEY || process.env.MOMO_SUBSCRIPTION_KEY;
const API_USER = process.env.MOMO_API_USER;
const API_KEY = process.env.MOMO_API_KEY;
const TARGET_ENV = process.env.MOMO_TARGET_ENVIRONMENT;     // 'sandbox' | 'mtnuganda'
const CALLBACK_URL = process.env.MOMO_CALLBACK_URL;

// The sandbox is not connected to a market and prices everything in EUR.
// Sending UGX there is rejected at MTN's edge with an HTML error page, not
// an API error, which is confusing to debug. Production takes the real
// currency.
const IS_SANDBOX = TARGET_ENV === 'sandbox';
const SANDBOX_CURRENCY = 'EUR';         // https://lizimasstore.com/webhooks/payments/mtn_momo

let tokenCache = { value: null, expiresAt: 0 };

async function getToken() {
  const now = Date.now();
  if (tokenCache.value && now < tokenCache.expiresAt) return tokenCache.value;

  const basic = Buffer.from(`${API_USER}:${API_KEY}`).toString('base64');
  const res = await fetch(`${BASE_URL}/collection/token/`, {
    method: 'POST',
    headers: {
      Authorization: `Basic ${basic}`,
      'Ocp-Apim-Subscription-Key': SUB_KEY,
    },
  });
  if (!res.ok) throw new Error(`momo_token_failed:${res.status}`);

  const data = await res.json();
  // Refresh a minute early rather than discovering expiry mid-checkout.
  tokenCache = {
    value: data.access_token,
    expiresAt: now + (Number(data.expires_in || 3600) - 60) * 1000,
  };
  return tokenCache.value;
}

/**
 * MTN returns `reason` as a bare string in sandbox. Some markets have been
 * reported returning {code, message}, so both shapes are handled.
 *
 * These strings are shown directly to the customer, so they're plain language,
 * not codes. Anything not in this map falls back to the raw code — ugly, but
 * better than a blank screen when MTN adds a reason we haven't seen.
 */
const MOMO_REASONS = {
  APPROVAL_REJECTED: 'You declined the payment request.',
  EXPIRED: 'The payment request timed out before it was approved.',
  PAYER_NOT_FOUND: 'That mobile money account could not be found.',
  PAYER_LIMIT_REACHED: 'Your mobile money transaction limit was reached.',
  NOT_ENOUGH_FUNDS: 'There was not enough money in the account.',
  PAYEE_NOT_ALLOWED_TO_RECEIVE: 'This store cannot receive payment from that account.',
  PAYER_NOT_ALLOWED_TO_SEND: 'That account is not allowed to send this payment.',
  INTERNAL_PROCESSING_ERROR: 'Mobile money had a problem processing the payment.',
  SERVICE_UNAVAILABLE: 'Mobile money is temporarily unavailable. Please try again shortly.',
  COULD_NOT_PERFORM_TRANSACTION: 'The payment could not be completed. Please try again.',
  TRANSFER_TYPE_UNKNOWN: 'The payment could not be completed. Please try again.',
  INVALID_CURRENCY: 'The payment could not be completed. Please contact support.',
  INVALID_CALLBACK_URL_HOST: 'The payment could not be completed. Please contact support.',
};

/** Normalises `reason` across both shapes MTN uses. */
function parseReason(reason) {
  if (!reason) return { code: null, message: null };
  if (typeof reason === 'string') {
    return { code: reason, message: MOMO_REASONS[reason] || reason };
  }
  const code = reason.code || null;
  return { code, message: reason.message || MOMO_REASONS[code] || null };
}

/**
 * MTN reports an unanswered prompt as status FAILED with reason EXPIRED, but
 * that's a materially different customer story from a declined or errored
 * payment — nobody said no, they just never looked at their phone. Promoting
 * it to our own `expired` state keeps that answerable with a status query
 * instead of a reason-string filter over the failures.
 */
function mapStatus(raw, reasonCode) {
  switch (String(raw || '').toUpperCase()) {
    case 'SUCCESSFUL': return STATUS.SUCCEEDED;
    case 'PENDING':    return STATUS.INITIATED;
    case 'FAILED':
      return reasonCode === 'EXPIRED' ? STATUS.EXPIRED : STATUS.FAILED;
    default:           return null;   // unknown -> leave the payment alone
  }
}

async function initiate({ externalRef, amountMinor, currency, msisdn, payerMessage, orderId }) {
  const token = await getToken();

  const body = {
    amount: String(amountMinor),
    currency: IS_SANDBOX ? SANDBOX_CURRENCY : currency,
    externalId: String(orderId),
    payer: {
      partyIdType: 'MSISDN',
      partyId: String(msisdn).replace(/^\+/, ''),   // MTN wants 256772123456
    },
    payerMessage: (payerMessage || 'Lizimas Store order').slice(0, 60),
    payeeNote: `Order ${orderId}`.slice(0, 60),
  };

  const res = await fetch(`${BASE_URL}/collection/v1_0/requesttopay`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'X-Reference-Id': externalRef,
      'X-Target-Environment': TARGET_ENV,
      'Ocp-Apim-Subscription-Key': SUB_KEY,
      'X-Callback-Url': CALLBACK_URL,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(body),
  });

  // 202 Accepted is the only success. Body is empty.
  if (res.status !== 202) {
    const text = await res.text().catch(() => '');
    throw new Error(`momo_requesttopay_failed:${res.status}:${text.slice(0, 200)}`);
  }

  return { providerRef: externalRef, accepted: true, raw: body };
}

async function fetchStatus({ externalRef }) {
  const token = await getToken();

  const res = await fetch(`${BASE_URL}/collection/v1_0/requesttopay/${externalRef}`, {
    headers: {
      Authorization: `Bearer ${token}`,
      'X-Target-Environment': TARGET_ENV,
      'Ocp-Apim-Subscription-Key': SUB_KEY,
    },
  });

  if (!res.ok) throw new Error(`momo_status_failed:${res.status}`);
  const data = await res.json();

  const reason = parseReason(data.reason);

  return {
    status: mapStatus(data.status, reason.code),
    rawStatus: data.status,
    amountMinor: data.amount != null ? Number(data.amount) : null,
    currency: data.currency,
    // MTN omits financialTransactionId on failures. Report null rather than
    // echoing our own reference back, so the column means what it says.
    providerRef: data.financialTransactionId || null,
    failureCode: reason.code,
    failureReason: reason.message,
    raw: data,
  };
}

/* --- webhook side --- */

// MTN sends no signature. We verify nothing and trust nothing; the route
// re-queries. Restrict by IP allowlist at Cloudflare if you want a second lock.
function verifyWebhook() {
  return true;
}

function extractEventKey(body, headers) {
  const ref = headers['x-reference-id'] || body?.externalId || '';
  const status = body?.status || '';
  if (ref && status) return `mtn:${ref}:${status}`;
  return `mtn:sha:${crypto.createHash('sha256').update(JSON.stringify(body || {})).digest('hex')}`;
}

function locatePayment(body, headers) {
  // MTN echoes the reference we generated.
  const ref = headers['x-reference-id'] || body?.referenceId || body?.externalId;
  return { externalRef: ref || null };
}

module.exports = {
  name: 'mtn_momo',
  MOMO_REASONS,
  // exported for unit tests
  _mapStatus: mapStatus,
  _parseReason: parseReason,
  supportsSignedWebhooks: false,
  initiate,
  fetchStatus,
  verifyWebhook,
  extractEventKey,
  locatePayment,
};
